name: Order Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "order-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./order-service
        run: npm install

      # Uncomment when tests are added
      # - name: Run Tests
      #   working-directory: ./order-service
      #   run: npm test

      # Uncomment if you add a build script
      # - name: Build Application
      #   working-directory: ./order-service
      #   run: npm run build